### PR TITLE
#90 Sidro update 2022.02.02

### PR DESCRIPTION
**Pull request by MV88**
Update project to [v2022.02.02](https://github.com/geosolutions-it/MapStore2/tree/v2022.02.02)

- removed majority of replacements in favor of plugin override
  - some of them have remained because it would have required a change in the core
- updated local files with the one coming from new version and re-applied over customizations
- backend part and resources are updated but I suggest to check them with a closer look @offtherailz 
- updated configs file and its location

test particularly embedded options for maps story dashboard

### CODE REVIEW

**Comment by MV88** [comment]
locally i have this error

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] MapStore2-C098 - Root Project 1.0-SNAPSHOT ......... SUCCESS [  0.180 s]
[INFO] Servizio Idrogeologico di Regione Toscana - WAR 1.0-SNAPSHOT FAILURE [  1.822 s]
[INFO] MapStore 2 - Backend Services 1.4.2 ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.214 s
[INFO] Finished at: 2023-01-13T12:28:34+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project MapStore2-C098-web: Failed to clean project: Failed to delete C:\Work\projects\Sidro\MapStore2-C098\web\target\cargo\installs\tomcat-8.5.69\apache-tomcat-8.5.69\lib\websocket-api.jar -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:   
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :MapStore2-C098-web
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MapStore2-C098@1.1.0 be:build: `mvn clean install -Pprinting`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MapStore2-C098@1.1.0 be:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2023-01-13T11_28_34_968Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MapStore2-C098@1.1.0 be:start: `npm run be:build && mvn cargo:run -f ./web/pom.xml`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MapStore2-C098@1.1.0 be:start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2023-01-13T11_28_34_988Z-debug.log
```

image

**Comment by ale-cristofori** [comment]
This PR is linked to the ticket #90

**Review by offtherailz — COMMENTED** [review]
I fixed the backend. Now you should be able to run it.
**notice** that I have 
- changed the port to 8080 dev port for backend in webpack config (to use be:start one)
- changed the name of the deliverable to mapstore.war
 

A summary of my changes: 

- add `.npmrc`
- Fixed webpack proxy
- [Here](https://webgis.cfr.toscana.it/mapstore/#/) is deployed as mapstore, so I should use mapstore also as `finalName` (and so need to replace it in all pom.xml paths (e.g `target/MapStore-c098` --> `target/mapstore`).  
- update `sample_categories.xml `
- Added missing xmls and dependencies. 

The rest looks good to my but I don't have time to test. Can you do it on your own ?

**Comment by MV88** [comment]
@ale-cristofori @offtherailz 
I tested it a bit but print plugin does not show up due to empty response from pdf/info.json request

I have updated a bit the pr, the war starts fine, but this printing issue is still present

**Comment by offtherailz** [comment]
Here some changes I [appllied](https://github.com/offtherailz/MapStore2-C098/commit/c071cf97742628055b6dacbd8915792afffcf9bc). I'm not able to merge, please check it. Basically I: 
- Aligned with template pom.xml (there was some deps that was not aligned)
- enabled printing by default

Please:
- Verify printing works now 
- Test also proxy properly working (I had issues but it may be a problem of my current java version, that is not aligned with the suggested for mapstore)

**Comment by MV88** [comment]
@offtherailz now printing module works in an external tomcat, but it does not work with embedded one

the info.json returns wrong url ,in my case i have this 
image

which is missing the port completely hence the error
image

**Comment by offtherailz** [comment]
The issue is known on MapStore and i think it is acceptable for the moment. 
If proxy and print work on tomcat, it is ok for me.

**Review by offtherailz — APPROVED** [review]
I reviewed and fixed mostly the back-end problems notified by and did a shallow review of the changes from github. 
I did no test (I can not actually) but all seems ok. Please @MV88 make you sure that the customization works as expected, or let me know if you need more help.

**Comment by ale-cristofori** [comment]
@randomorder, the war file for the upgraded mapStore has been uploaded to drive 
https://drive.google.com/drive/folders/1m02hRDWva83ChZE5mjFIZPuTEhdQn8QB
Please deploy it and let me know so that @ElenaGallo can start tests.

**Pull request merged**
